---
title: "My Digital Shadow"
output: html_notebook
author: Wenjia Zhai
---

```{r}
library(tidyverse)
library(lubridate)
library(ggrepel)
library(tools)
options(scipen = 999)
setwd("~/Google Drive/PPUA5302 Info Design & Visual Analytics/my_digital_shadows")
```

```{r}
mr <- read_csv("ActivityDetails.csv")
mr[47, 4] <- NA
mr <- mr[-c(3, 12, 31, 32, 48), ]
mr <- mr[seq(dim(mr)[1],1),]
# https://stackoverflow.com/questions/39975317/how-to-reverse-the-order-of-a-dataframe-in-r
```

```{r}
mr <- mr %>%
  mutate(Description = str_replace_all(Description, ".+ SPND", "Authorized User Offer")) %>%
  mutate(Description = str_replace_all(Description, ".+\\/.+", "Sign-up Bonus")) %>%
  mutate(Description = str_replace_all(Description, "Retention.+", "Retention")) %>%
  mutate(Description = str_replace_all(Description, "Targeted Spend & Get Offers", "Targeted Spend Offers")) %>%
  mutate(Description = str_replace_all(Description, "20% Extra Points Apr 2018", "Spend Reward")) %>%
  mutate(Description = str_replace_all(Description, ".+\\-\\d+", "Spend Reward")) %>%
  mutate(Description = str_replace_all(Description, "Amazon 3X Membership Rewards", "Spend Reward")) %>%
  mutate(Description = str_replace_all(Description, "Amex Express Checkout Offer", "Spend Reward")) %>%
  mutate(Description = str_replace_all(Description, "Points Adjustment", "Spend Reward")) %>%
    mutate(Date = str_replace_all(mdy(Date), "(\\d+-\\d+)-\\d+", "\\1"))
```

```{r}
mr2 <- mr %>%
  group_by(Description) %>%
  summarise("Total Points" = sum(Points, na.rm = T))
```

```{r}
pie(mr2$`Total Points`, labels = mr2$`Total Points`, main = "Total Points Earned", col = rainbow(length(mr2$`Total Points`)))
legend("topright", mr2$Description, cex = 0.8, fill = rainbow(length(mr2$`Total Points`)))
# https://www.tutorialspoint.com/r/r_pie_charts.htm
```

```{r}
mr %>%
  group_by(Date) %>%
  summarise(Points = sum(Points, na.rm = T)) %>%
  ggplot(aes(Date, cumsum(Points), group = 1)) +
    geom_line(color = "red") +
    geom_point(color = "blue") +
    geom_text_repel(aes(Date, cumsum(Points), label = paste("Earn Points:", Points, "\nTotal Points:", cumsum(Points)), vjust = -1)) +
    theme(panel.grid.minor.y = element_blank(), panel.background = element_blank(), panel.grid.major.y = element_line(colour = "grey95"), panel.grid.minor.x = element_blank(), panel.grid.major.x = element_line(color = "grey95")) +
    ylab("Total Points") + coord_cartesian(ylim = c(0, 450000)) +
  ggtitle(label = "The Points Accumulation")
#https://stackoverflow.com/questions/15844919/cumulative-plot-using-ggplot2
```

```{r}
mr %>%
  filter(Description == "Spend Reward") %>%
  group_by(multiple) %>%
  summarise(`Multiple Earn` = sum(points, na.rm = T), `General Earn` = sum(Points, na.rm = T) - `Multiple Earn`) %>%
  gather(-multiple, key = `earn rate`, value = `points earned`) %>%
  ggplot(aes(multiple, `points earned`, fill = `earn rate`)) +
    geom_col(position = "dodge") +
    geom_label_repel(aes(multiple, `points earned`, label = paste(`points earned`, "points")), show.legend = F) +
  ylab("Points Earned") + xlab("Rate") + guides(fill=guide_legend(title="Earning Rate")) +
  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank()) +
  ggtitle(label = "Comparison Between Different Earning Rate")
# https://stackoverflow.com/questions/14622421/how-to-change-legend-title-in-ggplot
```

```{r}
plat <- read_csv("Plat.csv")
schwab <- read_csv("Plat_Swchab.csv")
mb <- read_csv("Plat_MB.csv")
plat_am <- read_csv("Plat_Am.csv")
prg <- read_csv("PRG.csv")
gold_am <- read_csv("PRG_Am.csv")
green <- read_csv("Green.csv")

plat$type <- "Platinum Card"
schwab$type <- "Platinum Card for Charlse Schwab"
mb$type <- "Platinum Card for Mecerdes Benz"
plat_am$type <- "Platinum Card for Ameriprise"
prg$type <- "Gold Card"
gold_am$type <- "Gold Card for Ameriprise"
green$type <- "Green Card"

complete <- bind_rows(plat, schwab, mb, plat_am, prg, gold_am, green)
complete <- complete %>%
  select(Description, Amount, type) %>%
  filter(!str_detect(Description, "PARTNERS HEALTHCARE|THANK YOU")) %>%
  mutate(Description = str_replace(Description, "(AMERICAN AIRLINES).+", "\\1")) %>%
  mutate(Description = str_replace_all(Description, "GIFT.+", "Gift Card")) %>%
  mutate(Description = str_replace_all(Description, "(AMAZON).+", "\\1")) %>%
  mutate(Description = str_replace_all(Description, ".+(ITUNES).+", "\\1")) %>%
  mutate(Description = str_replace(Description, "MCDONALD'S", "McDonald's")) %>%
  mutate(Description = str_replace_all(Description, "(WALMART).+", "\\1")) %>%
  mutate(Description = str_replace_all(Description, "VZWIRELESS.+", "Verizon")) %>%
  mutate(Description = str_replace_all(Description, "SAKS.+", "Saks Fifth Ave")) %>%
  mutate(Description = str_replace_all(Description, "(DELTA AIR LINES).+", "\\1")) %>%
  mutate(Description = str_replace_all(Description, "(7-ELEVEN).+", "\\1")) %>%
  mutate(Description = str_replace_all(Description, "SEAMLSS.+", "Seamless")) %>%
  mutate(Description = toTitleCase(tolower(Description)))

charge <- complete %>%
  filter(Amount > 0, !str_detect(Description, "Interest"))

credit <- complete %>%
  filter(Amount < 0) %>%
  mutate(Amount = as.numeric(str_replace_all(Amount, "-(.+)", "\\1")),
         Description = str_replace_all(Description, ".+(Hilton Gift Card)", "\\1")) %>%
  group_by(Description, Amount, type) %>%
  summarise(Total = sum(Amount)) %>%
  filter(Total > 9)
```

```{r}
ggplot(charge, aes(Description, Amount, fill = type)) +
  geom_col(position = "dodge") + 
  guides(fill=guide_legend(title="Credit Card")) +
  ggtitle(label = "Credit Card Charge") +
  theme(panel.grid.minor.y = element_blank(), axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
ggplot(credit, aes(Description, Total, fill = type)) +
  geom_col(position = "dodge") + 
  guides(fill=guide_legend(title="Credit Card")) +
  ggtitle(label = "Credit Card Reimbursement") +
  theme(panel.grid.minor.y = element_blank(), axis.text.x = element_text(angle = 90, hjust = 1), axis.title.x = element_blank())
```

